#! /bin/bash

# get the coaster service address
coasterurl=$(cat swift.conf | grep URL | sed "s/URL: \"//g" | sed "s/\"//")

dprepro $1 input.template input.in

echo $coasterurl
swift_driver "python p1.py" "$coasterurl"
#python p1.py

cp results.txt $2

