#! /bin/bash

# get the coaster service address
coasterurl=$(cat swift.conf | grep URL | sed "s/URL: \"//g" | sed "s/\"//")

dprepro $1 input.template input.in --output-format="%f"
#echo "inlet5_X,5,inlet6_Y,7" > input.in
cat input.in


#tar xvf transferin.tar
#chmod 777 -R *
#./utils/runOpenfoam.sh sample_inputs/elbow.tgz sample_inputs/elbow.pvsm $(cat input.in) out.tgz out.png













#just create results.txt file to register it for transfer
echo "placeholder" > $(cat input.in).tar.gz
echo "placeholder" > results.txt



echo $coasterurl

#swift_driver "python p1.py" "$coasterurl"
#ls
#echo "tar xvf transferin.tar"  > untar_and_runofa.sh
#echo "./utils/runOpenfoam.sh sample_inputs/elbow.tgz sample_inputs/elbow.pvsm $(cat input.in) out.tgz out.png"  >> untar_and_runofa.sh

chmod 777 -R *

#swift_driver "./utils/runOpenfoam.sh sample_inputs/elbow.tgz sample_inputs/elbow.pvsm $(cat input.in) out.tgz out.png" "$coasterurl"

swift_driver "untar_and_run.sh sample_inputs/elbow.tgz null $(cat input.in) out.tgz null" "$coasterurl"

#swift_driver "chmod 777 -R *" "$coasterurl"
#cat output.txt
#swift_driver "ls -fl" "$coasterurl"
#ls -fl

cat output.txt
cat sim.log
cat results.txt
ls -fl
#python p1.py
#cat input.in

cp results.txt $2

